settings:
  title: 'RH - Status'
  url: 'https://status.ronkkeli.app/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Servers / Locations up'
  notAllmonitorsOperational: 'Not all servers / locations online.'
  monitorLabelOperational: 'All servers / locations operational'
  monitorLabelNotOperational: 'Something is wrong...'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All servers and locations up.'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: game1
    name: rh-1.ronkkeli.net
    description: 'game1.ronkkeli.app'

    url: 'https://game-1-status.ronkkeli.app/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: false;
 
